-- Exact function signatures nikalne ke liye ye query run karo
SELECT 
    proname as function_name,
    pg_get_function_identity_arguments(p.oid) as parameters,
    'ALTER FUNCTION public.' || proname || '(' || pg_get_function_identity_arguments(p.oid) || ') SET search_path = '''';' as exact_fix_command
FROM pg_proc p
WHERE p.pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public')
AND proname IN (
    'check_and_update_expired_access',
    'generate_and_increment_invoice_no',
    'generate_and_increment_job_card_no',
    'generate_invoice_no',
    'get_all_users_with_session_count',
    'get_booking_summary',
    'get_dashboard_stats',
    'get_financial_year',
    'get_follow_ups_v2',
    'get_follow_ups_v3',
    'get_invoice_summary',
    'get_invoice_summary_v2',
    'get_next_invoice_number_v2',
    'get_next_job_card_invoice_no_v2',
    'get_party_ledger',
    'get_party_ledger_v2',
    'get_party_sale_summary',
    'get_party_vehicle_invoice_summary',
    'get_party_wise_sale_report',
    'get_party_wise_sale_report_v2',
    'get_sales_by_salesperson',
    'get_user_role',
    'get_vehicle_invoices_report',
    'get_vehicle_invoices_report_v2',
    'get_vehicle_invoices_report_v3',
    'get_vehicle_invoices_report_v4',
    'handle_new_user_default_role',
    'handle_stock_deletion_on_sale',
    'handle_updated_at',
    'is_premium_tools_admin',
    'manage_wp_return',
    'manage_ws_return',
    'normalize_access_keys',
    'record_invoice_gap',
    'save_job_card_and_update_inventory',
    'search_vehicle_invoices',
    'search_vehicle_invoices_v2',
    'search_vehicle_invoices_v3',
    'search_vehicle_invoices_v4',
    'search_vehicle_invoices_v5',
    'sync_sold_stock',
    'track_job_card_history',
    'track_vehicle_history',
    'track_vehicle_history_v2',
    'track_vehicle_history_v3',
    'track_vehicle_history_v4',
    'track_vehicle_history_v5',
    'track_vehicle_history_v6',
    'track_vehicle_history_v7',
    'track_vehicle_history_v8',
    'track_vehicle_history_v9',
    'track_vehicle_history_v10',
    'track_vehicle_history_v11',
    'track_vehicle_history_v12',
    'track_vehicle_history_v13',
    'update_inventory_from_purchases',
    'update_inventory_item_quantity',
    'upsert_and_update_inventory'
)
ORDER BY proname;